### ISSUE TITLE
Add Data Context

### ISSUE THREAD

**Issue by anabranch** [california-civic-data-coalition/django-calaccess-raw-data#101]
One of the things that I think is so hard about working with this data is understanding what I am working with. 

I feel it would really help contributions if you could understand what exactly this data represents and what kinds of questions can and can't be answered with it. The column names and tables are so arcane that any lay developer needs a ton of expertise/time to be able to get their hands dirty with working with this data.

It'd be great to have a journalist/someone with writing skill add this sort of information into the documentation. What is this data, what does it mean, what does it show?

**Comment by palewire** [comment]
Like I said in the other repo, you're totally right on this. Though the path to getting there is going to be slow and paved by a thousand little commits. 

Now that we have the download, extract and load tasks handled, it's tempting to think we're done. And I wish it was as easy as just stapling a couple paragraphs on top of the docs. 

The painful reality is we are sitting on a massive, poorly documented and strangely designed government database that ingests records from a weird array of overlapping reporting requirements.

To make progress on this, we need to chip away at documenting what exactly all the fields and tables are in the database, as you can see many of the tickets here do, and then use out campaign and lobbying browser apps to automate and document the proper, accurate ways to extract meaningful data out of this big muddy pool. 

If you want to chip in, check out our current docs, where you can find the government manual describing every table in this repo. There's a lot of field descriptions, code lookups and other materials in there that ultimately need to port into our humanized docs and Python docstrings, Django choices fields etc. 

On the campaign browser end, all of the queries we've written so far to pull out filers, filings, contribs, etc., need proofing, optimization and expansion.

When we get all this dirty work done, we're going to have some great bulk downloads with docs that people can pick up and run with. But we've got a lot of spadework to do before we get there. Which is why open source collaboration is so vital to this project. Without it, we'd all be on our own.
