### ISSUE TITLE
Add docstring to FilersCd model

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#116]
* [Model](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/other.py#L78)
* [Docs](http://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p107)

**Comment by mhkeller** [comment]
I got it.

**Comment by mhkeller** [comment]
This looks like a typo to me, it should read "all links and associations" instead of "all linkls and assocations". Just to double check @palewire / @aboutaaron , `linkls` isn't a thing in this database right? It should be `links`.

![screen shot 2015-03-05 at 16 01 10 pm](https://cloud.githubusercontent.com/assets/498744/6514492/dfdf1bf8-c350-11e4-9bb9-54ecb7a5f045.png)

**Comment by mhkeller** [comment]
Aaron confirmed this is a typo.
