### ISSUE TITLE
Upgrade managements commands to use Django's new args/kwargs system

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1169]
Starting with Django 1.8, [a new system for configuring custom arguments](https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/#accepting-optional-arguments) and options on management commands was introduced. 

At some point Django's developers are likely to deprecate the old system and, as discussed in #1158, we aren't thrilled with all of our current options. 

So at some point we should port our current commands forward to the new regime.

**Comment by gordonje** [comment]
loadcalaccessrawfile has a `--app-name` option which defaults to `calaccess_raw`. This option isn't documented in mastercommands.rst. What's the rationale for this option? Do users expect the load command to work for other apps?

**Comment by gordonje** [comment]
Here are what understand to be the differences between the old and new way of setting up options for custom management commands:

1.    Instead of using optparse, use argparse;
2.    Instead implementing a set_options method on the sub-classed command, implement an add_arguments method;
3.    Instead of defining options in a global variable using make_option, define them within the command's add_arguments method using add_argument;
4.    Both args and kwargs are passed in through **options to the command's handle method.

So that's basically what I've done. Originally, I was a little more ambitious with what I might re-factor, but I've walked that back as I've realized that these probably require more discussion. I will propose these separately.

Other changes included in this PR:

1.    Both `cleancalaccessrawfile` and `loadcalaccessrawfile` were previously sub-classing LabelCommand, but are now sub-classing the BaseCommand. Long-story-short: LabelCommand doesn't seem to be working correctly with custom options (submitted a [StackOverflow question](https://stackoverflow.com/questions/34842191/django-using-labelcommand-with-options) on this), and anyway BaseCommand seems more straight-forward.
2.    In `downloadcalaccessrawdata` I've erased any remaining vestiages of the old clear options. Now there's only a `--keep-files` option which maps to `self.keep_files`, and the command's other methods check this attribute so that the kwarg doesn't need to be continually passed around.

(Submitting a pull request so that @palewire and @bcipolli can look things over before I merge these to master).

**Comment by bcipolli** [comment]
Haven't read the code, but I'm a huge fan of the changes from a high-level. Just one question: what's the minimum django version that this will be compatible with?

**Comment by palewire** [comment]
Our aim with the upcoming release has been to support Django>=1.8. I thought that might be the way to go because it is also the current level of backwards support offered by Django itself, [as documented here](https://www.djangoproject.com/download/).

**Comment by bcipolli** [comment]
:+1:

**Comment by gordonje** [comment]
It's possible I went a little too far with this last commit and un-did something crucial to @bcipolli's work in PR #1158. Your feedback / proposals are welcome.
