### ISSUE TITLE
downloadcalaccessrawdata does much more than its name would have us believe

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1182]
Our master command, ``downloadcalaccessrawdata``, is in fact doing much more than downloading the files. It is also cleaning them and loading the result into a database. This imprecision in naming sucks. 

Following the refactor of #1181, I propose that we abstract out the downloading of the ZIP file into a separate management command as we have already done with the other key components of the routine, namely ``loadcalaccessrawdata`` and ``cleancalaccessrawdata``.

The proposal: The current download command will be renamed as ``updatecalaccessrawdata`` and would continue to run through the full download, clean, load cycle. But the existing download mechanism would be refactored into a new management command, which could perhaps keep ``downloadcalaccessraw`` namespace. 

That newly separated download routine could then be invoked inside of the update command, as the clean and load routines already are. Or run separately on its own if that's what you want to do.

The clear advantages of this that I see would be that we would have a better, more accurate name for our master command, and each of its three components would be handled in the same way. Everything would be easier to read and grok. Bugfixes, tests and updates to the components could also be handled separately. 

I understand this change will cause complications for current downstream users like @bcipolli, but my hope is that after we iron out the wrinkles in the ugly first draft of these commands it will ultimately yield a simplified design that will make subclassing and reuse of the underlying components easier long into the future.

**Comment by bcipolli** [comment]
@bcipolli welcomes these downstream issues :+1: Our code has even greater issues with naming, and having a clean upstream system will ... enable us to address them more promptly!

**Comment by palewire** [comment]
@aboutaaron, do you have any thoughts on this?

**Comment by aboutaaron** [comment]
@palewire totally agree with these changes. I'm all for making this process as simple and slim as possible. Also, you can now reload the data without re-downloading the snapshot from the FTP or passing an array for cli flags. :100:

**Comment by gordonje** [comment]
Unless any of you feel otherwise, I'm going to leave what we are currently calling the download prompt within the newly named `updatecalaccessrawdata` command as opposed to moving it into the new / leaner `downloadcalaccessrawdata` command.

If we were going to move it, then I think we should consider adding similar prompts to the other commands. We don't necessarily have to be consistent with all commands, but I wonder why the download step deserves a prompt while the others don't.

**Comment by gordonje** [comment]
Actually...this is a little problematic. The prompt relies on the remote and local metadata (i.e., the time of the last download and time the last file was posted). Seems like all that should live in the download command so that it's being written regardless of whether or not the user runs `updatecalaccessrawdata` or `downloadcalaccessrawdata`.

Relatedly: Resume seems like an option that should be available when running `updatecalaccessrawdata` or `downloadcalaccessrawdata`.

Okay, so I'm a flip-flopper. The prompt goes with the new download command.

Maybe the other commands also want prompts, tracking of past jobs and resuming of previous jobs. Let's make separate tickets for those if we think they are valuable.

**Comment by gordonje** [comment]
And I think `--keep-files` becomes an option on each of three more discrete commands:

*    download (by default remove the zip file and unzipped dir)
*    clean (by default remove the "dirty" tsv file after it's cleaned)
*    load (by default remove the "clean" csv file after it's loaded)

**Comment by palewire** [comment]
I agree that putting the prompt in the new separate download command is good. I think it makes sense to give people a warning before they download such a big file, and we should already have Django's standard ``--noinput`` flag for users who want to always skip it.

**Comment by gordonje** [comment]
@palewire: Interesting. I can see the `--noinput` option on [django's base command](https://github.com/django/django/blob/5f7f3b46853c958789361a7defda8ca3c3c2be53/django/core/management/commands/migrate.py#L33) but can't access it in my custom handle() method with `options['interactive]`. 

Verbosity works, I don't have to define that for each of our commands.

**Comment by palewire** [comment]
Ah. I added our own noinput option [here](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/downloadcalaccessrawdata.py#L123-L129) and probably screwed it up. I didn't realize it was on the base command all along.
