### ISSUE TITLE
startup confusions

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#1186]
Sorry about this, but I am trying to come back to see how things are and I am not able to migrate. I have been using the version (fork? copy?) of your code that the caciviclab has and that is working for me. But I may want to fork this instead.

I have tried installing a few times, in different ways, including my own document I wrote for the caciviclab people (https://docs.google.com/document/d/1rQfHDM_wdOX2W38U44Iuv9341UmcIJgocqUICXR6soA/edit). But I am using MacOS X now and not Ubuntu. So there may be a platform thing I missed.

I keep seeing the same result:

     $ python manage.py migrate
     Traceback (most recent call last):
       File "manage.py", line 10, in <module>
         execute_from_command_line(sys.argv)
       File "/Users/rkiddy/Projects/openCA/cacivicdata/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
         utility.execute()
       File "/Users/rkiddy/Projects/openCA/cacivicdata/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
         django.setup()
       File "/Users/rkiddy/Projects/openCA/cacivicdata/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
         apps.populate(settings.INSTALLED_APPS)
       File "/Users/rkiddy/Projects/openCA/cacivicdata/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
         app_config = AppConfig.create(entry)
       File "/Users/rkiddy/Projects/openCA/cacivicdata/env/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
         module = import_module(entry)
       File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
         __import__(name)
       File "/Users/rkiddy/Projects/openCA/cacivicdata/env/lib/python2.7/site-packages/calaccess_raw/__init__.py", line 3, in <module>
         from django.db.models.loading import get_models, get_app
     ImportError: No module named loading

Is there something obvious that I have forgotten? Has anything changed that might not be documented yet? Is a particular version of Django required?

**Comment by aboutaaron** [comment]
It could be a Django version issue. Did you reinstall the required libraries? 
```
$ pip install -r requirements
```

**Comment by gordonje** [comment]
@rkiddy We're Django>=1.8 now. You're probably running Django 1.9? You should probably also `git pull` our latest changes. I believe this issue was addressed in the last few weeks. Let us know if you need more info or if you're still having issues.

**Comment by rkiddy** [comment]
I will check this. But there are two cases here.

In one case, I do a "git clone" and get a copy of the project. And then I would expect to install the stuff in the requirements_dev.txt file.

But the other is where I am just installing the project. For that, I would do a "pip install" of this project and ... would the package itself be responsible for its requirements? I am not expert on python packaging.

The "How to Use it" document says one can do:

     pip install django-calaccess-campaign-browser
     python manage.py migrate

So, if one just wants to install and use it, there must be more to do, no?

**Comment by gordonje** [comment]
Oh, I see @rkiddy. You are talking about using [django-calaccess-campaign-browser](http://django-calaccess-campaign-browser.californiacivicdata.org/en/latest/index.html) as opposed to the [django-calaccess-raw-data](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/index.html) which is the repo under which you filed this ticket is filed.

But that's mostly on us, as we're still striving to articulate exactly what purpose each app is intended to serve and how they are chainable yet clearly distinguishable.

The raw-data app is the code for downloading, cleaning and loading the CAL-ACCESS data into a database so that you can begin to query it. And the campaign-browser app depends on the raw-data app.

As @aboutaaron suggests, you'll get this error if you're running the current version of Django (that's 1.9.1) and the previous version of django-calaccess-raw-data (that's 0.1.2). 

In fact, [today we just released](http://www.californiacivicdata.org/2016/01/25/raw-data-0.2.0-release/) v0.2.0 of the raw-data app. But unfortunately, you can't solve this problem by upgrading to our current version because we've made the decision for that code to be compliant with Django versions >= 1.8. Base on some cursory tests, the campaign-browser is only working on Django 1.7. 

So if you want to keep using the campaign-browser app, you'll need to downgrade Django:
```
pip install django==1.7
```
Then also run:
```
pip show django-calaccess-raw-data
```
Just to confirm that you are running the previous version of the raw-data app. You should see:
```
Name: django-calaccess-raw-data
Version: 0.1.2
Location: /Users/<YOUR_OS_USERNAME>/.virtualenvs/django-calaccess-campaign-browser/lib/python2.7/site-packages
Requires: django, csvkit, python-dateutil, argparse, requests, clint, hurry.filesize
```
Then commands like `python example/manage.py migrate` and `python example/manage.py downcalaccessrawdata` should start working for you.

However, I suggest you switch to using and contributing to our raw-data app because that's where all the action is right now. The future of the campaign-browser is rather nebulous and, while I am going to file tickets for the issues you've uncovered, I doubt we'll be addressing them even within the next two months (@palewire and @aboutaaron may want to check me on this). 

Our more immediate plans involving migrating much of the browser-app's code into another new app that's narrowly focused on processing the raw CAL-ACCESS data into more rational data models.

Here are the [instructions](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/howtocontribute.html) for getting started with the raw-data app.

Sorry for the confusion, and thanks for bearing with us through the early stages of our project.

**Comment by gordonje** [comment]
Oh hey, and @rkiddy: You should also consider joining our on-going conversation on the #california-civic-data channel of the [News Nerdery](http://newsnerdery.org/) Slack. Most of us are hanging out there all the time. Just email [Daniel Bachhuber](mailto:d@danielbachhuber.com) about signing up.

**Comment by gordonje** [comment]
I filed [this campaign-browser ticket](https://github.com/california-civic-data-coalition/django-calaccess-campaign-browser/issues/236).

**Comment by rkiddy** [comment]
I have gotten around my issues. Yes, the link to the 1.8+ compatibility is a good thing.
