### ISSUE TITLE
README.md looks like crap on PyPI

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1187]

**Comment by bcipolli** [comment]
link?

**Comment by gordonje** [comment]
Any reason we can't make our README an .rst file? That's what [elex](https://github.com/newsdev/elex/) is doing, and both theirs looks good on both pypi and GitHub.

**Comment by palewire** [comment]
No reason.

**Comment by gordonje** [comment]
I used [Pandoc](http://pandoc.org/index.html) to easily convert README.md to README.rst, and pushed that change. Looks good on GitHub, and we can check out on PyPi whenever we do our next release (see #1193).

Drawing from [this example](http://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work/26737672#26737672), if we prefer to keep writing this and other docs whatever docs we can in markdown, we can also use [pypandoc](https://pypi.python.org/pypi/pypandoc/) to read markdown and write it out as rst.

Seems like we could get away with this without introducing the new dependencies to our end users, since this is only relevant for auto-generating the PKG-INFO file whenever we create new distributions. We would add the following to setup.py:

```python
try:
    import pypandoc
    long_description = pypandoc.convert('README.md', 'rst')
except(IOError, ImportError, OSError):
    long_description = open('README.md').read()
```
Then further down when we call the setup function:
```python
setup(
    ...
    long_description = long_description,
    ...
```

We might want to look into it down the road, maybe also for our other user docs which are currently in rst.

Apparently [the discussion](https://bitbucket.org/pypa/pypi/issues/148/support-markdown-for-readmes%22%20rel=%22nofollow) about moving PyPi away from rst to md has been going on for years, with several entrenched interests at odds.

**Comment by palewire** [comment]
Great. Feel free to try the long_description thing.

**Comment by gordonje** [comment]
On second thought: Since every other doc we've written is .rst (and I've gotten a lot more used to it), we'll just continue doing everything in .rst without having to mess with any conversions.
