### ISSUE TITLE
Add unit test for archiving

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-raw-data#1314]
Thought a little more about this, and here's my initial proposal.

The hurdle is that, currently, none of our unit tests touch the tracking models where the archive FileFields exist. I made that choice early on to avoid the complexity of not overwriting / polluting the tracking models with test data. These models have pretty tight constraints (e.g., foreign key and unique) that are not amenable to fake records.

So to tackle all that, here's the path I see:

1. Add a unit test for making a request to the .zip file export, and create (if necessary) a RawDataVersion with the `last-modified` date in the response header. This action might even be performed by `downloadcalaccessrawdata` if the user runs that command with a `--test` option. Granted, the test data will probably have been sampled from an early version of the data, but I can't see how that matters, and we certainly don't want to perform the entire download as part of any test.
2. We could then allow the download and clean commands to create or get RawDataFile records tied to the currently available version. When the download and clean commands are in test-mode, we can just save the test files with a prefix, like `test_ACRONYMS.TSV` to wherever the archive files are configured to be saved. Then, if the full data files are in the archive directory, we'll have to re-save those in the FileFields (**be careful to ensure that the full data files are not deleted when running these commands in test mode**).
3. When the download, clean and load commands are in test mode, we should also skip the step where we update RawDataFiles various record and column count columns.
4.  We could also allow test runs of the management commands to create RawDataCommand records too, because...why not. But if we are going to, then I like the idea of adding a boolean RawDataCommand.is_test field so that the tests are easily distinguishable from the normal operations of the app. But none of this is super-pertinent to the issue at hand.

I believe this approach accomplishes our goal of ensuring that we can archive files in any combination of Django and Python that we are supporting. And it has the added benefit of testing the creation and use of the tracking models, which currently are not being tested.

Only possible downside I see is that we're going to end up adding a `--test` option to all these commands. Perhaps it would be less offensive if we just added that option on the base command.

@palewire What do you think?

**Comment by gordonje** [comment]
Alternative, we could just have one simple test that:

1. Creates the RawDataVersion (if it's not there) for any date, maybe the date that comes from the export url (does it even matter?)
2. Attempts to save a test file to RawDataVersion.zip_file_archive field
3. Re-saves the actual zip file for that version back into RawDataVersion.zip_file_archive (if it's there)
4. (maybe repeat these steps for the RawDataFile FileFields)

This approach would effectively test whether or not our archiving scheme is working in all supported environments.

Even though this approach is much less work, I think I prefer my first proposal (WHAT THE HELL IS WRONG WITH ME) because the commands and tracking models will all be more throughly tested and it's an opportunity to clean out some code that's not super-intuitive.

**Comment by palewire** [comment]
Alternative idea: **A test subclass of our management commands** that use the sampled data from the local filesystem and are only called via the command line option or a subclassing.

01. Write a subclassed version of ``downloadcalaccessrawdata`` with its [download](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/downloadcalaccessrawdata.py#L192-L221) method replaced with a test version that simply copied a new ginned up ZIP of test data to the ``self.zip_path`` rather than downloading it from the state. 
02. We'd remove all of the if clauses that no prevent logging of test data 
03. Figure out a way for the download subclass to be called from ``updatecalaccessrawdata`` via either the existing command-line argument, or a direct call to the subclasses from the unittests. 
04. Everything besides the download operates as expect and the test data gets loaded into your database and tracked and archived
