### ISSUE TITLE
Remind me why we save the column counts in the database?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1486]

**Comment by gordonje** [comment]
Yeah, we aren't really surfacing these counts anywhere on the website, and I doubt these numbers are as important to the users are the counts of records. 

I recall adding it because it's yet another way that the raw data files could potentially change from one snapshot to the next, and that we might want to count the number of delimited fields each time we process a file and make sure it equals the number of fields on the table we are loading (minus the unique id we add).

I'm not sure what errors (if any) the postgres COPY FROM and mysql LOAD INTO statements might throw if the number of fields in the input does not match the number fields on the target table, but the behavior of will almost definitely be inconsistent.

One other check we could add is post-load, does the target table have any columns that are completely NULL? But actually...I think that's true for some of these junkier tables anyway, so we would have to consider how to deal with that.

I think we can safely say, though, that we have yet so see the SoS add or subtract fields from the raw data files. But having kept track of these counts helps us confirm that.

```sql
SELECT raw_files.*, db_tables.real_column_count
FROM (
        SELECT 
                file_name, 
                count(*) as release_count, 
                sum(download_columns_count) as download_columns_sum,
                sum(clean_columns_count) as clean_columns_sum,
                sum(download_columns_count) / count(*) as avg_download_col_count,
                sum(clean_columns_count) / count(*) as avg_clean_col_count
        FROM calaccess_raw_rawdatafile
        GROUP BY file_name
        -- exclude consistently empty files
        HAVING sum(download_columns_count) > 0
) as raw_files
JOIN (
        SELECT table_name, count(*) as real_column_count
        FROM information_schema.columns
        where column_name <> 'id'
        GROUP BY table_name
) as db_tables
ON raw_files.file_name = db_tables.table_name;
```
The three numbers at the far right of this result set should be equal. I ran this on the prod db server and thankfully, they are.
