### ISSUE TITLE
Create a separate row-counting management commmand for proofing imports ad hoc

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#48]
Could potentially log the counts in a dedicated database table

**Comment by rkiddy** [comment]
Can you expand a little bit on what you mean by this? If I understand what you are getting at, it may be something I can implement.

Are you talking about logical checks of the data, such as if there are x of this type of row in one table, there should be y rows matching it in some other table? Or are you thinking something else?

**Comment by palewire** [comment]
It's not anything too high priority. It got added when I was generating as many tickets as possible for our "code rush" in Atlanta. My poorly formed thought was that if we split out a counting routing we could automate some kind of integrity check/report at the end of the load. I'm open for whatever seems worth doing to you.

**Comment by palewire** [comment]
It's not anything too high priority. It got added when I was generating as many tickets as possible for our "code rush" in Atlanta. My poorly formed thought was that if we split out a counting routine we could automate some kind of integrity check/report at the end of the load. I'm open for whatever seems worth doing to you.

**Comment by rkiddy** [comment]
I mentioned this in another context, but it may be relevant here. You all process the TSV files into CSV files and import them, and then there are some number of rejected rows.

I add pk to the front of each line in each TSV file. This would then be translated to the CSV file and, after telling django not to use automatic pk values, into the table.

The benefit of this is that one can then see, for any row in the database, which line of the TSV it came from. Once I did this, I was able to figure out a way to correct the files so that all the data got loaded. Whatever corrections end up getting made or not made, it is still extremely helpful to see which specific lines in the files have problems and what the problems are.

**Comment by palewire** [comment]
That's a good approach. We have a logger right now that is dumping all the bum rows out for inspection there.

What kind of corrections were necessary?

**Comment by rkiddy** [comment]
Well, I have some code doing some corrections, but this is not the approach I would suggest now. And it is not in python. My bad. :-)

See https://github.com/rkiddy/OpenCalAccessData/blob/master/00_fix_dload_files

You can see corrections I do in every row in the "usual fixes" sub at line 111.

If you page down, you will see fixes specific to particular files. These are very ad hoc, so keep that in mind. Don't ask me to defend the code, but it is what it is and it is what my scripts call still.

**Comment by palewire** [comment]
Eh. We probably don't need this.
