### ISSUE TITLE
Add Python 3 support and testing

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#77]

**Comment by myersjustinc** [comment]
I'll take a crack at this one.

**Comment by myersjustinc** [comment]
Working on this in my [py3-compat branch](https://github.com/myersjustinc/django-calaccess-raw-data/tree/py3-compat). I've made a couple of commits there to get `manage.py shell` and `manage.py migrate` working properly.

Just to make sure I understand the scope of this properly: This repo's mainly about its management commands, right? (The rest of the big stuff is in the campaign browser repo?)

**Comment by myersjustinc** [comment]
Starting to keep track here of other incompatibilities as I come across them:

* Download confirmation prompt shows a bytestring `repr` rather than a properly formatted message: [downloadcalaccessdata.py](https://github.com/myersjustinc/django-calaccess-raw-data/blob/7572871887ccb02c1f6a734826108699bc7e2d90/calaccess_raw/management/commands/downloadcalaccessrawdata.py#L107)
* `set_local_metadata` tries to write a string to a binary file without encoding it first: [downloadcalaccessdata.py](https://github.com/myersjustinc/django-calaccess-raw-data/blob/7572871887ccb02c1f6a734826108699bc7e2d90/calaccess_raw/management/commands/downloadcalaccessrawdata.py#L160)

**Comment by aboutaaron** [comment]
I believe this has landed!
